<a href="https://colab.research.google.com/github/bhavyasri23-dev/bhavyasri23-dev/blob/main/numpy06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy


In [2]:
import numpy as np


In [18]:
array1d=np.array([1,2,3,4,5,6,7,8,9])
print(array1d)

[1 2 3 4 5 6 7 8 9]


one dimensional array

In [4]:
array2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array2d)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Two dimensional array

In [5]:
zero_arr=np.zeros((2,5))
print(zero_arr)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


zeros

In [6]:
one_arr=np.ones((3,5))
print(one_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


ones


In [7]:
iden_arr=np.eye(5)
print(iden_arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


identity matrix

In [8]:
arange_arr=np.arange(1,10,2)
print(arange_arr)

[1 3 5 7 9]


arange operation

In [25]:
random=np.random.random((2,5))
print(random)

[[0.48591292 0.09055486 0.0070823  0.4175944  0.25144203]
 [0.37247757 0.58155184 0.0452333  0.1382601  0.90739261]]


In [31]:
random1=np.random.randint(2,10)
print(random1)

9


random

In [35]:
slice=np.array([10,20,30,40,50])
print(slice[0:3])
print(slice[::4])

[10 20 30]
[10 50]


slicing

In [13]:
index=np.array([1,2,3,4,5,6,7])
print(index[3])

4


index

In [47]:
linspc=np.linspace(0,1,7)
print(linspc)

[0.   0.25 0.5  0.75 1.  ]


In [23]:
rev_arr=np.array([1,4,7,8,9])
print(rev_arr[::-1])

[9 8 7 4 1]


linespacing

In [15]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
add_array=np.add(arr1,arr2)
print(add_array)

[5 7 9]


add two matrices

In [34]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
sub_array=np.subtract(arr1,arr2)
print(sub_array)
mul_array=np.multiply(arr1,arr2)
print(mul_array)
div_arr=np.divide(arr1,arr2)
print(div_arr)
pow_arr=np.power(arr1,4)
print(pow_arr)

[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[  1  16  81 256]


In [78]:
arr1=np.random.randint(10,51,size=(4,5))
print(arr1)



[[40 13 33 37 17]
 [16 36 26 24 49]
 [38 18 12 43 28]
 [11 12 46 28 43]]


In [79]:
print(arr1[1:3])

[[16 36 26 24 49]
 [38 18 12 43 28]]


In [81]:
arr1[arr1%2==0]=-1
print(arr1)

[[-1 13 33 37 17]
 [-1 -1 -1 -1 49]
 [-1 -1 -1 43 -1]
 [11 -1 -1 -1 43]]


In [89]:
np.sum(arr1,axis=1)

array([99, 45, 39, 51])